server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bidemy
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 4GB
      max-request-size: 4GB


  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    com.bidemy: DEBUG

video:
  storage:
    path: C:/Users/Zeynep/Documents/uploads

image:
  storage:
    path: C:/Users/Zeynep/Documents/course_images
