server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bidemy
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
